
import asyncio
import json
from unittest.mock import MagicMock, patch
from datetime import datetime
from core.midterm_plan_engine import MidtermPlanEngine
from core.schemas.midterm_plan_schema import CorporatePhilosophy, GenerationMetadata

# Mock OpenAI Response
class MockChoice:
    def __init__(self, content, finish_reason="stop"):
        self.message = MagicMock(content=content)
        self.finish_reason = finish_reason

class MockUsage:
    def __init__(self):
        self.prompt_tokens = 100
        self.completion_tokens = 50
        self.total_tokens = 150

class MockResponse:
    def __init__(self, content):
        self.choices = [MockChoice(content)]
        self.usage = MockUsage()
        self.model = "gpt-4o-mock"
        self.system_fingerprint = "fp_mock123"

async def test_metadata_capture():
    print("Starting Metadata Capture Test...")
    
    # 1. Setup Engine and Inputs
    engine = MidtermPlanEngine()
    
    # Dummy data ensuring valid JSON output
    dummy_output = {
        "narrative": "Test narrative generated by mock.",
        "data": {
            "mission": "To test the audit system.",
            "core_values": [" Integrity", "Innovation"]
        }
    }
    
    # 2. Mock OpenAI Client
    with patch("core.midterm_plan_engine.openai_client") as mock_openai:
        mock_openai.chat.completions.create.return_value = MockResponse(json.dumps(dummy_output))
        
        # 3. Call private method _call_llm_for_section to test the logic
        # We need to bypass the public generate_section_01 etc to control inputs directly or call a specific one
        # Let's call _call_llm_for_section directly as it contains the logic we changed
        
        try:
            section = await engine._call_llm_for_section(
                prompt="Test prompt",
                expected_model=CorporatePhilosophy
            )
            
            # 4. Assertions
            print(f"Section Generated: {section.section_title}")
            
            if section.generation_metadata:
                print("✅ Generation Metadata found!")
                print(f"   Model: {section.generation_metadata.model_name}")
                print(f"   Fingerprint: {section.generation_metadata.system_fingerprint}")
                print(f"   Usage: {section.generation_metadata.usage}")
                print(f"   Timestamp: {section.generation_metadata.generated_at}")
                
                assert section.generation_metadata.model_name == "gpt-4o-mock"
                assert section.generation_metadata.system_fingerprint == "fp_mock123"
                assert section.generation_metadata.usage["total_tokens"] == 150
            else:
                print("❌ Generation Metadata MISSING!")
                exit(1)
                
        except Exception as e:
            print(f"❌ Test Failed with Exception: {e}")
            import traceback
            traceback.print_exc()
            exit(1)

if __name__ == "__main__":
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    loop.run_until_complete(test_metadata_capture())
